// apps/dashboard/src/app/features/audit/audit-log-page/audit-log-page.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuditService } from '../../../core/services/audit.service';
import { LucideAngularModule } from 'lucide-angular';

@Component({
    selector: 'app-audit-log-page',
    standalone: true,
    imports: [CommonModule, LucideAngularModule],
    template: `
    <div class="space-y-6">
      <div class="flex justify-between items-center">
        <h1 class="text-2xl font-bold text-gray-900">Audit Log</h1>
      </div>

      @if (auditService.isLoading()) {
        <div class="text-center py-10 text-gray-500">Loading audit logs...</div>
      } @else if (logs().length === 0) {
        <div class="text-center py-10 bg-white rounded-lg border border-gray-200 text-gray-500">
          No audit logs found.
        </div>
      } @else {
        <div class="bg-white shadow-sm border border-gray-200 rounded-lg overflow-hidden">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User ID</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Resource</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Timestamp</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              @for (log of logs(); track log.id) {
                <tr class="hover:bg-gray-50 transition-colors">
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600 font-mono">{{ log.userId.slice(0, 8) }}...</td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm">
                    <span [class]="'px-2 py-1 rounded-full text-xs font-medium ' + getActionClass(log.action)">
                      {{ log.action }}
                    </span>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {{ log.resourceType }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ log.timestamp | date:'medium' }}
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
    </div>
  `,
    styles: [`
    :host { display: block; }
  `]
})
export class AuditLogPageComponent implements OnInit {
    public auditService = inject(AuditService);

    logs = this.auditService.logs;

    ngOnInit() {
        this.auditService.fetchLogs();
    }

    getActionClass(action: string): string {
        switch (action.toLowerCase()) {
            case 'create': return 'bg-green-50 text-green-700';
            case 'update': return 'bg-blue-50 text-blue-700';
            case 'delete': return 'bg-red-50 text-red-700';
            default: return 'bg-gray-50 text-gray-700';
        }
    }
}

// src/features/audit/AuditLogPage.tsx

import React, { useEffect, useState } from 'react';
import { api } from '../../core/api';
import type { AuditLog } from '../../types';
import { Clock, User as UserIcon, Activity } from 'lucide-react';

export const AuditLogPage: React.FC = () => {
    const [logs, setLogs] = useState<AuditLog[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchLogs = async () => {
            try {
                const res = await api.get<AuditLog[]>('/audit-log');
                setLogs(res.data);
            } catch (err) {
                console.error('Failed to fetch audit logs');
            } finally {
                setLoading(false);
            }
        };

        fetchLogs();
    }, []);

    return (
        <div className="space-y-6">
            <h1 className="text-2xl font-bold text-gray-900">Audit Log</h1>

            <div className="bg-white shadow-sm overflow-hidden rounded-lg border border-gray-200">
                <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                        <tr>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Time</th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Resource</th>
                        </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                        {loading ? (
                            <tr>
                                <td colSpan={4} className="px-6 py-4 text-center text-gray-500">Loading logs...</td>
                            </tr>
                        ) : logs.map((log) => (
                            <tr key={log.id} className="hover:bg-gray-50">
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 flex items-center gap-2">
                                    <Clock size={16} />
                                    {new Date(log.timestamp).toLocaleString()}
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <div className="flex items-center gap-2">
                                        <UserIcon size={16} className="text-gray-400" />
                                        {log.userId}
                                    </div>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <span className={`px-2 py-1 text-xs font-medium rounded-full ${log.action === 'DELETE' ? 'bg-red-100 text-red-800' :
                                        log.action === 'CREATE' ? 'bg-green-100 text-green-800' :
                                            'bg-blue-100 text-blue-800'
                                        }`}>
                                        {log.action}
                                    </span>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 flex items-center gap-2">
                                    <Activity size={16} />
                                    {log.resourceType} {log.resourceId ? `(${log.resourceId})` : ''}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};
